name: Build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -B build -DWARNINGS_AS_ERRORS=1
    - name: make
      run: (cd build; make)
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -B build -DWARNINGS_AS_ERRORS=1
    - name: make
      run: (cd build; make)
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: cmake
      run: cmake -B build -G "NMake Makefiles" -DWARNINGS_AS_ERRORS=1
    - name: nmake
      run: |
        cd build
        nmake

